include:
  - compose/local/db.yml
  - compose/local/app.yml

networks:
  default:
    name: bodycam_local
    ipam:
      config:
        - subnet: 172.28.0.0/24

volumes:
  postgres_data:
  redis_data:
  minio_data:
